### ISSUE TITLE
Can't create a task

### ISSUE THREAD

**Issue by BorisHruby** [1ft-seabass/node-red-contrib-todoist#1]
Hello,

I've been trying to make the Todoist task creation in Node-RED work for two days already, but without success and I'm really desperate now. I have Node-RED version 1.0.3. Simply installed the node from the palette, took the example flow from here and put my Todoist token into it. The task was processed but with error (see below). Do you have any idea what could be the problem?
Thanks a lot in advance.

Have a nice day,

Boris

INJECTED PAYLOAD:

{"content":"Appointment with Maria","due_string":"tomorrow at 12:00","due_lang":"en","priority":4}

RESPONSE OBJECT:

{"statusCode":410,"body":"Please use https://api.todoist.com/rest/v1/ endpoint.\nSee https://developer.todoist.com/rest/v1/ for details.","headers":{"content-type":"text/plain; charset=utf-8","content-length":"109","connection":"close","server":"awselb/2.0","date":"Wed, 29 Jan 2020 19:19:19 GMT","x-cache":"Error from cloudfront","via":"1.1 0b828d2972235c5e8de186e29f1866fd.cloudfront.net (CloudFront)","x-amz-cf-pop":"VIE50-C1","x-amz-cf-id":"87KzAKCqVzLv6p01WqUnfTAiIclgCzqQ83vCpylhJ7Hc9iD_jp8DXw=="},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"beta.todoist.com","port":443,"hostname":"beta.todoist.com","hash":null,"search":null,"query":null,"pathname":"/API/v8/tasks","path":"/API/v8/tasks","href":"https://beta.todoist.com/API/v8/tasks"},"method":"POST","headers":{"Content-Type":"application/json","X-Request-Id":1580325558968462.5,"Authorization":"Bearer \"_HERE WAS MY TOKEN_\"","accept":"application/json","content-length":98}}}

**Comment by 1ft-seabass** [comment]
Hi. Thank you for using my node! I try also your flow json :) Please wait for a few days.

I have a question, just in case. Do you already have own todoist API token already? Is ```"Authorization":"Bearer "HERE WAS MY TOKEN"``` part is your own todoist API token?

And I will also check the latest todoist API release status again later.

**Comment by BorisHruby** [comment]
Hi!
Thanks for your quick answer. I'd really appreciate if you take a look into it and make it work. Thanks in advance for your effort.
I took the Todoist API token from my Todoist account (Settings/Integrations at the very bottom). In the list I sent you I replaced it of course ;-)

**Comment by 1ft-seabass** [comment]
Thank you for your reply! I see about your token. I'm checking this issue flow now. And I see its background gradually. I will be able to fix this probably. 👍

**Comment by 1ft-seabass** [comment]
@BorisHruby Hi. I saw that this issue occured for no changing to the latest Todoist endpoint. So I changed it at https://github.com/1ft-seabass/node-red-contrib-todoist/commit/01c4d44d1773f21e1d73c21a2b1b774078c68c5e . Thank you for your reporting!

And I updated version 0.0.6. It already can use from flow.nodered.org and Node-RED palette manager. Would you please use latest the node?

**Comment by BorisHruby** [comment]
Many thanks! I'll test it in couple of days, I'm on my holiday now. Looking 
forward to it!

**Comment by 1ft-seabass** [comment]
Of course! Have a nice holiday!

**Comment by BorisHruby** [comment]
Hey! Works like a charm now! Many thanks!
Have a nice day,

Boris

**Comment by 1ft-seabass** [comment]
Thank you for your checking! I was relieved!

And I'm closing this issue just now.
